#!/bin/bash

# If no argument is provided, read URL from clipboard
if [ "$#" -eq 0 ]; then
    echo "Reading from clipboard"
    URL="$(xclip -selection clipboard -o)"
else
    echo "Reading from argument"
    URL="$@"
fi

# Start mpv and record its PID
mpv "$URL" --quiet >/dev/null &
PID=$!

# Start an infinite while loop to run while mpv is still running
while true; do
    sleep 0.2
    if kill -0 $PID; then # check mpv is still running
        if xdotool search --pid $PID; then # check when mpv has an open window
            if xdotool windowfocus $(xdotool search --pid $PID); then # focus the open window and run several tasks
                i3-msg floating enable
                i3-msg sticky toggle
                movit bottom right -b 3 -s 3
                exit 0
            fi 
        fi
    else
        exit 1 # end the script early if mpv ends
    fi
done
